name: test React app
on: 
  pull_request:
    types:
       - opened  
  workflow_dispatch:
  push:
    branches:
       - main
       - 'hotfix-*'
       - 'feature/**'
#path-ignore:
 #       - '.github/workflows/*'   
# ex: hotfix-fix-ajout
# ex: feature/fix/ajout/../
# la ligne de permission est propre au build et au deployement
permissions:
  contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Code
              uses: actions/checkout@v3
            - name: install Node v21.1.0
              uses: actions/setup-node@v3
              with:
                node-version: 21.1.0
            - name: Install
              run: npm install
            - name: Test
              run: npm test
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Code
            uses: actions/checkout@v3
          - name: install Node v21.1.0
            uses: actions/setup-node@v3
            with:
             node-version: 21.1.0
          - name: Install
            run: npm install
          - name: Build
            run: npm run build
    deploy:          
      runs-on: ubuntu-latest
      steps:
          - name: Code
            uses: actions/checkout@v3
          - name: install Node v21.1.0
            uses: actions/setup-node@v3
            with:
                node-version: 21.1.0
          - name: Install
            run: npm install          
          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@v4       
            with:
              folder: build
              branch: gh-reactruth
          
