name: test React app
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Code
              uses: action/checkout@v3
            - name: install Node v21.1.0
              uses: actions/setup-node@v3
              with:
                node-version: 21.1.0
            - name: Install
              run: npm install
            - name: Test
              run: npm test
            