name: test React app
on: 
  pull_request:
    types:
       - opened  
  workflow_dispatch:
  push:
    branches:
       - main
       - 'hotfix-*'
       - 'feature/**'
#path-ignore:
 #       - '.github/workflows/*'   
# ex: hotfix-fix-ajout
# ex: feature/fix/ajout/../

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Code
              uses: actions/checkout@v3
            - name: install Node v21.1.0
              uses: actions/setup-node@v3
              with:
                node-version: 21.1.0
            - name: Install
              run: npm install
            - name: Test
              run: npm test
            